apiVersion: apps/v1
kind: Deployment
metadata:
  name: konveyor
  labels:
    app: konveyor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konveyor
  template:
    metadata:
      labels:
        app: konveyor
    spec:
      containers:
        - name: konveyor
          image: 046222885654.dkr.ecr.eu-central-1.amazonaws.com/konveyor:$IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
